# redpanda-statefulset.yaml: Redpanda StatefulSet và Service để triển khai Redpanda Kafka Broker trên K3s
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  annotations:
    description: "Redpanda StatefulSet for high-performance Kafka-compatible message broker"
  labels:
    app: redpanda
spec:
  serviceName: redpanda-service
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      nodeSelector:
        workload-type: worker
      containers:
      - name: redpanda
        image: docker.redpanda.com/redpandadata/redpanda:v23.3.21
        args:
        - start
        - --overprovisioned
        - --smp
        - "1"
        - --memory
        - 1G
        - --reserve-memory
        - 0M
        - --kafka-addr
        - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
        - --advertise-kafka-addr
        - PLAINTEXT://redpanda-0.redpanda-service.mlops-redpanda.svc.cluster.local:9092,OUTSIDE://localhost:19092
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 19092
          name: kafka-ext
        - containerPort: 9644
          name: admin
        resources:
          # Ép xung tự bảo vệ: Không để Redpanda hút cạn RAM của Worker Node.
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: redpanda-data
          mountPath: /var/lib/redpanda/data
  volumeClaimTemplates:
  - metadata:
      name: redpanda-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi

# Tạo Service để expose Redpanda Kafka Broker
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-service
spec:
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka
  - port: 19092
    targetPort: 19092
    name: kafka-ext
  - port: 9644
    targetPort: 9644
    name: admin
  clusterIP: None
  selector:
    app: redpanda
