apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-prod-cluster-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
  labels:
    mlops-paas.io/plane: cluster
    mlops-paas.io/component: storage
spec:
  project: mlops-cluster
  info:
    - name: Owner
      value: Platform Engineering
    - name: Source
      value: k8s/cluster/storage
    - name: Runbook
      value: https://github.com/Viet-Hoang-2005/MLOps-paas-system/blob/main/k8s/README.md#cluster
  source:
    repoURL: https://github.com/Viet-Hoang-2005/MLOps-paas-system.git
    targetRevision: main
    path: k8s/cluster/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-cluster-config
