apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlops-consumer

resources:
- ../../../base/consumer
- external-secrets.yaml

images:
- name: mlops-paas-consumer
  newName: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-consumer
  newTag: 4b51df12edb86192e1c7e6f97cd600680eb92dde
