# Generated by Django 5.0.3 on 2026-09-15 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('ct', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('trigger_kind', models.CharField(choices=[('manual', 'Manual'), ('retry', 'Retry'), ('maintenance', 'Maintenance')], default='manual', max_length=32)),
                ('recipe_version', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('model_flavor', models.CharField(choices=[('sklearn', 'Scikit-learn'), ('xgboost', 'XGBoost'), ('pytorch', 'PyTorch'), ('tensorflow', 'TensorFlow')], max_length=40)),
                ('entry_point', models.CharField(default='train.py', max_length=512)),
                ('requirements_text', models.TextField(blank=True)),
                ('code_snapshot_uri', models.CharField(max_length=1024)),
                ('data_snapshot_uri', models.CharField(max_length=1024)),
                ('output_uri', models.CharField(max_length=1024)),
                ('mlflow_artifact_uri', models.CharField(blank=True, max_length=1024)),
                ('mlflow_run_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('backend', models.CharField(default='local', max_length=30)),
                ('external_job_id', models.CharField(blank=True, max_length=255)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('uploading', 'Uploading'), ('running', 'Running'), ('cancelling', 'Cancelling'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('vcpu', models.PositiveIntegerField(default=2)),
                ('memory_mb', models.PositiveIntegerField(default=4096)),
                ('max_runtime_seconds', models.PositiveIntegerField(default=3600)),
                ('accelerator_type', models.CharField(choices=[('none', 'None'), ('gpu', 'GPU')], default='none', max_length=20)),
                ('accelerator_count', models.PositiveIntegerField(default=0)),
                ('tracking', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('runtime_seconds', models.PositiveIntegerField(default=0)),
                ('outputs_purged_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_requested_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deletion_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_training_jobs', to='registry.modelversion')),
                ('dataset_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_jobs', to='ct.datasetsnapshot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='catalog.modelproject')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='training.trainingjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingJobCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('output_upload', 'Output upload'), ('trusted_reporter', 'Trusted reporter'), ('cancel_reporter', 'Cancellation reporter')], max_length=40)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='training.trainingjob')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('model', 'Model'), ('metric', 'Metric'), ('insight', 'Insight'), ('file', 'File')], default='file', max_length=30)),
                ('relative_path', models.CharField(max_length=512)),
                ('s3_uri', models.CharField(max_length=1024)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='training.trainingjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['project', 'status'], name='training_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingjobcapability',
            index=models.Index(fields=['job', 'purpose', 'expires_at'], name='training_capability_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingoutput',
            constraint=models.UniqueConstraint(fields=('job', 'relative_path'), name='training_output_path_unique'),
        ),
    ]
