# Generated by Django 5.0.3 on 2026-09-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingoutput',
            name='kind',
            field=models.CharField(choices=[('model', 'Model'), ('reference_data', 'Reference Data'), ('metric', 'Metric'), ('insight', 'Insight'), ('file', 'File')], default='file', max_length=30),
        ),
    ]
