# Generated by Django 5.0.3 on 2026-07-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingJobCapability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("purpose", models.CharField(choices=[("output_upload", "Output upload"), ("trusted_reporter", "Trusted reporter")], max_length=40)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="capabilities", to="training.trainingjob")),
            ],
        ),
        migrations.AddIndex(
            model_name="trainingjobcapability",
            index=models.Index(fields=["job", "purpose", "expires_at"], name="training_capability_idx"),
        ),
    ]
