# Generated by Django 5.0.3 on 2026-10-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingjob",
            name="reference_path",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="reference_snapshot_uri",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
