# Generated by Django 5.0.3 on 2026-10-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingjob_reference_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingjob',
            name='reference_path',
        ),
        migrations.RemoveField(
            model_name='trainingjob',
            name='reference_snapshot_uri',
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='output_revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trainingoutput',
            name='kind',
            field=models.CharField(choices=[('model', 'Model'), ('metric', 'Metric'), ('insight', 'Insight'), ('source_code', 'Source Code'), ('reference_data', 'Reference Data'), ('file', 'File')], default='file', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='trainingoutput',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['source_code', 'reference_data'])), fields=('job', 'kind'), name='training_output_unique_supplemental_kind'),
        ),
    ]
