# consumer-deployment.yaml: Triển khai Kafka Consumer để tiêu thụ dữ liệu từ Redpanda và phát hiện Data Drift với Evidently
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-paas-consumer
  annotations:
    description: "Kafka Consumer to process network traffic data in batches and store predictions"
  labels:
    app: mlops-paas-consumer
spec:
  # Consumer chỉ cần 1 replica (dùng kafka group consumer) là đủ để dọn dẹp
  replicas: 1
  selector:
    matchLabels:
      app: mlops-paas-consumer
  template:
    metadata:
      labels:
        app: mlops-paas-consumer
    spec:
      nodeSelector:
        workload-type: worker
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mlops-paas-consumer
                topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: init-kafka-topic
          image: docker.redpanda.com/redpandadata/redpanda:v23.3.21
          command: ["/bin/sh", "-c"]
          args: ["rpk topic create mlops_paas_production_data --brokers redpanda-service.mlops-redpanda.svc.cluster.local:9092 || true"]
      containers:
        - name: consumer
          image: mlops-paas-consumer
          imagePullPolicy: Always
          command: ["python", "-m", "src.main"]
          envFrom:
            - configMapRef:
                name: mlops-paas-consumer-config
          env:
            - name: CONTROL_PLANE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: consumer-secret
                  key: CONTROL_PLANE_WEBHOOK_SECRET
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: consumer-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: consumer-secret
                  key: DB_PASSWORD
          # Cấu hình tài nguyên cho Consumer
          resources:
            requests:
              cpu: 150m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 768Mi
