apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlops-web

resources:
- ../../../base/web

images:
- name: mlops-paas-web
  newName: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-web
  newTag: 1816fbd8d6bf40fb8b67ea76b87bc011b74b19db
