# cluster-secret-store.yaml: Cấu hình kết nối giữa K3s và AWS Secrets Manager
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
        # Không cần khai báo Token, ESO sẽ tự động xin quyền từ IAM Role đã gắn vào EC2 Worker Node
        # (Thông qua Instance Metadata Service - IMDS)
