apiVersion: v1
kind: Namespace
metadata:
  name: mlops-cluster-config
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops-control-plane
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops-consumer
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops-model-server
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops-web
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops-postgres
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops-redis
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops-redpanda
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops-execution
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops-model-runtimes
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlops-routing
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare
---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow-server
  labels:
    app: mlflow-server
---
apiVersion: v1
kind: Namespace
metadata:
  name: user-jobs
---
apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
