# Generated by Django 5.0.3 on 2026-07-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='allowed_projects',
            field=models.ManyToManyField(blank=True, related_name='api_keys', to='catalog.modelproject'),
        ),
    ]
