apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-prod-platform-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    mlops-paas.io/plane: platform
    mlops-paas.io/component: redis
spec:
  project: mlops-platform
  info:
    - name: Owner
      value: Platform Engineering
    - name: Source
      value: k8s/platform/redis
    - name: Runbook
      value: https://github.com/Viet-Hoang-2005/MLOps-paas-system/blob/main/k8s/README.md#redis
  source:
    repoURL: https://github.com/Viet-Hoang-2005/MLOps-paas-system.git
    targetRevision: main
    path: k8s/platform/redis
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-redis
