apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlops-control-plane

resources:
- ../../../base/control-plane
- external-secrets.yaml

images:
- name: mlops-paas-control-plane
  newName: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-control-plane
  newTag: ae4cca7d932f6caf96bcf4966f08a39f23487c1d
