apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlops-control-plane

resources:
- ../../../base/control-plane
- external-secrets.yaml

images:
- name: mlops-paas-control-plane
  newName: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-control-plane
  newTag: ff3d02d0cb7b55589a3998e78bfd260e0f130f00
