apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-prod-addon-argo-workflows
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    mlops-paas.io/plane: addon
    mlops-paas.io/component: argo-workflows
spec:
  project: mlops-addons
  info:
    - name: Owner
      value: Platform Engineering
    - name: Source
      value: argoproj.github.io/argo-helm/argo-workflows@0.45.11
    - name: Runbook
      value: https://github.com/Viet-Hoang-2005/MLOps-paas-system/blob/main/k8s/README.md#addons
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 0.45.11
    helm:
      releaseName: argo-workflows
      values: |
        crds:
          install: true
        controller:
          workflowNamespaces:
            - mlops-execution
            - argo
          workflowRestrictions:
            templateReferencing: Secure
          nodeSelector:
            workload-type: worker
        server:
          nodeSelector:
            workload-type: worker
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
