apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-prod-addon-cloudnative-pg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    mlops-paas.io/plane: addon
    mlops-paas.io/component: cloudnative-pg
spec:
  project: mlops-addons
  info:
    - name: Owner
      value: Platform Engineering
    - name: Source
      value: cloudnative-pg.github.io/charts/cloudnative-pg@0.24.0
    - name: Runbook
      value: https://github.com/Viet-Hoang-2005/MLOps-paas-system/blob/main/k8s/README.md#addons
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.24.0
    helm:
      releaseName: cloudnative-pg
      values: |
        nodeSelector:
          workload-type: worker
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
