apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-prod-addon-karpenter-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
  labels:
    app.kubernetes.io/part-of: mlops-paas
    mlops-paas.io/environment: production
    mlops-paas.io/plane: addon
    mlops-paas.io/component: karpenter-crds
spec:
  project: mlops-addons
  info:
    - name: Owner
      value: Platform Engineering
    - name: Source
      value: public.ecr.aws/karpenter/karpenter-crd@1.13.0
    - name: Runbook
      value: https://github.com/Viet-Hoang-2005/MLOps-paas-system/blob/main/k8s/README.md#addons
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter-crd
    targetRevision: 1.13.0
    helm:
      releaseName: karpenter-crd
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - PruneLast=true
      - FailOnSharedResource=true
