apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-prod-addon-keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  labels:
    mlops-paas.io/plane: addon
    mlops-paas.io/component: keda
spec:
  project: mlops-addons
  info:
    - name: Owner
      value: Platform Engineering
    - name: Source
      value: kedacore.github.io/charts/keda@2.17.2
    - name: Runbook
      value: https://github.com/Viet-Hoang-2005/MLOps-paas-system/blob/main/k8s/README.md#addons
  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: 2.17.2
    helm:
      releaseName: keda
      values: |
        nodeSelector:
          workload-type: worker
        metricsServer:
          nodeSelector:
            workload-type: worker
        webhooks:
          nodeSelector:
            workload-type: worker
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
