apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aws-ebs-csi.yaml
  - external-secrets.yaml
  - cloudnative-pg.yaml
  - keda.yaml
  - argo-workflows.yaml
  - argo-events.yaml
  - monitoring.yaml
  - kyverno.yaml
  - karpenter-crds.yaml
  - karpenter.yaml
  - kubeflow-training.yaml
  - node-feature-discovery.yaml
  - gpu-operator.yaml
