# Generated by Django 5.0.3 on 2026-09-15 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('source', 'Source'), ('training_output', 'Training Output'), ('package', 'Package'), ('label_mapping', 'Label Mapping'), ('mlflow', 'MLflow'), ('image', 'Image'), ('metrics', 'Metrics'), ('params', 'Parameters'), ('model_insights', 'Model Insights'), ('feature_importance', 'Feature Importance'), ('input_schema', 'Input Schema')], max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=1024)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('value', models.FloatField()),
                ('step', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('dataset_role', models.CharField(choices=[('training', 'Training'), ('calibration', 'Calibration'), ('reference', 'Reference'), ('gate', 'Gate'), ('historical_holdout', 'Historical holdout')], default='training', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RegistryAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_job_reference', models.UUIDField(blank=True, db_index=True, null=True)),
                ('version', models.CharField(max_length=80)),
                ('requirements_snapshot', models.TextField(blank=True)),
                ('flavor', models.CharField(blank=True, max_length=80)),
                ('stage', models.CharField(choices=[('none', 'None'), ('staging', 'Staging'), ('production', 'Production'), ('archived', 'Archived')], default='none', max_length=20)),
                ('deployability', models.CharField(choices=[('unknown', 'Unknown'), ('deployable', 'Deployable'), ('track_only', 'Track Only'), ('invalid', 'Invalid')], default='unknown', max_length=30)),
                ('deployability_reason', models.TextField(blank=True)),
                ('metrics_summary', models.JSONField(blank=True, default=dict)),
                ('params_summary', models.JSONField(blank=True, default=dict)),
                ('insights_summary', models.JSONField(blank=True, default=dict)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.modelproject')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
