# Generated by Django 5.0.3 on 2026-07-12 03:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.CharField(max_length=80)),
                ('requirements_snapshot', models.TextField(blank=True)),
                ('flavor', models.CharField(blank=True, max_length=80)),
                ('stage', models.CharField(choices=[('none', 'None'), ('staging', 'Staging'), ('production', 'Production'), ('archived', 'Archived')], default='none', max_length=20)),
                ('deployability', models.CharField(choices=[('unknown', 'Unknown'), ('deployable', 'Deployable'), ('track_only', 'Track Only'), ('invalid', 'Invalid')], default='unknown', max_length=30)),
                ('deployability_reason', models.TextField(blank=True)),
                ('metrics_summary', models.JSONField(blank=True, default=dict)),
                ('params_summary', models.JSONField(blank=True, default=dict)),
                ('insights_summary', models.JSONField(blank=True, default=dict)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.modelproject')),
                ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_versions', to='training.trainingjob')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('value', models.FloatField()),
                ('step', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='registry.modelversion')),
            ],
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('source', 'Source'), ('training_output', 'Training Output'), ('package', 'Package'), ('label_mapping', 'Label Mapping'), ('mlflow', 'MLflow'), ('image', 'Image'), ('metrics', 'Metrics'), ('params', 'Parameters'), ('model_insights', 'Model Insights'), ('feature_importance', 'Feature Importance'), ('input_schema', 'Input Schema')], max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=1024)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='registry.modelversion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistryAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.modelproject')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='registry.modelversion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(max_length=60)),
                ('from_state', models.CharField(blank=True, max_length=80)),
                ('to_state', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='registry.modelversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='modelversion',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='registry_project_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='modelversion',
            constraint=models.UniqueConstraint(
                condition=models.Q(('source_job__isnull', False)),
                fields=('source_job',),
                name='registry_source_job_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='modelartifact',
            constraint=models.UniqueConstraint(fields=('version', 'kind', 'name'), name='registry_artifact_unique'),
        ),
        migrations.AddConstraint(
            model_name='registryalias',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='registry_project_alias_unique'),
        ),
    ]
