# Generated by Django 5.0.3 on 2026-09-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('registry', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='source_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_versions', to='training.trainingjob'),
        ),
        migrations.AddField(
            model_name='modelmetric',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='registry.modelversion'),
        ),
        migrations.AddField(
            model_name='modelartifact',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='registry.modelversion'),
        ),
        migrations.AddField(
            model_name='registryalias',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.modelproject'),
        ),
        migrations.AddField(
            model_name='registryalias',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='registry.modelversion'),
        ),
        migrations.AddConstraint(
            model_name='modelversion',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='registry_project_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='modelversion',
            constraint=models.UniqueConstraint(condition=models.Q(('source_job__isnull', False)), fields=('source_job',), name='registry_source_job_unique'),
        ),
        migrations.AddConstraint(
            model_name='modelartifact',
            constraint=models.UniqueConstraint(fields=('version', 'kind', 'name'), name='registry_artifact_unique'),
        ),
        migrations.AddConstraint(
            model_name='registryalias',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='registry_project_alias_unique'),
        ),
    ]
