# Generated by Django 5.0.3 on 2026-09-23 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct', '0002_initial'),
        ('registry', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='reference_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_versions', to='ct.datasetsnapshot'),
        ),
        migrations.AlterField(
            model_name='modelartifact',
            name='kind',
            field=models.CharField(choices=[('model', 'Model'), ('reference_data', 'Reference Data'), ('source', 'Source'), ('training_output', 'Training Output'), ('package', 'Package'), ('label_mapping', 'Label Mapping'), ('mlflow', 'MLflow'), ('image', 'Image'), ('metrics', 'Metrics'), ('params', 'Parameters'), ('model_insights', 'Model Insights'), ('feature_importance', 'Feature Importance'), ('input_schema', 'Input Schema'), ('data_contract', 'Data Contract')], max_length=40),
        ),
    ]
