# Generated by Django 5.0.3 on 2026-10-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="modelversion",
            name="registry_source_job_unique",
        ),
        migrations.AlterField(
            model_name="modelartifact",
            name="kind",
            field=models.CharField(
                choices=[
                    ("source", "Source"),
                    ("source_code", "Source Code"),
                    ("reference_data", "Reference Data"),
                    ("training_output", "Training Output"),
                    ("package", "Package"),
                    ("label_mapping", "Label Mapping"),
                    ("mlflow", "MLflow"),
                    ("image", "Image"),
                    ("metrics", "Metrics"),
                    ("params", "Parameters"),
                    ("model_insights", "Model Insights"),
                    ("feature_importance", "Feature Importance"),
                    ("input_schema", "Input Schema"),
                ],
                max_length=40,
            ),
        ),
    ]
