# Generated by Django 5.0.3 on 2026-10-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_remove_modelversion_registry_source_job_unique_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='modelartifact',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['source_code', 'reference_data'])), fields=('version', 'kind'), name='registry_artifact_unique_supplemental_kind'),
        ),
    ]
