# Generated by Django 5.0.3 on 2026-09-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_modelartifact_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelartifact',
            name='kind',
            field=models.CharField(choices=[('model', 'Model'), ('reference_data', 'Reference Data'), ('source_code', 'Source Code'), ('package', 'Package'), ('label_mapping', 'Label Mapping'), ('mlflow', 'MLflow'), ('image', 'Image'), ('metrics', 'Metrics'), ('params', 'Parameters'), ('model_insights', 'Model Insights'), ('feature_importance', 'Feature Importance'), ('input_schema', 'Input Schema'), ('data_contract', 'Data Contract')], max_length=40),
        ),
    ]
