# pod-disruption-budgets.yaml: Bảo vệ các service khỏi downtime khi bảo trì node (kubectl drain)
# 1. PDB cho Django Control Plane
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mlops-paas-control-plane-pdb
  namespace: mlops-control-plane
spec:
  minAvailable: 1 # Luôn giữ ít nhất 1 Pod phục vụ API
  selector:
    matchLabels:
      app: mlops-paas-control-plane
---
# 2. PDB cho Cloudflare Tunnel
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudflared-pdb
  namespace: cloudflare
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cloudflared
---
# 3. PDB cho Frontend Web
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mlops-paas-web-pdb
  namespace: mlops-web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mlops-paas-web
---
