apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-paas-control-plane-config
  labels:
    app: mlops-paas-control-plane
data:
  PYTHONUNBUFFERED: "1"
  PYTHONPATH: "/app/src"
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  DB_HOST_RW: "mlops-paas-postgres-rw.mlops-postgres.svc.cluster.local"
  DB_HOST_RO: "mlops-paas-postgres-ro.mlops-postgres.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "mlops_paas_db"
  DB_SCHEMA: "control_plane"
  CONTROL_PLANE_DB_SCHEMA: "control_plane"
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0,control-plane,mlops-paas-control-plane,mlops_paas_control_plane,api.mlops-nids-nt114.id.vn"
  EXECUTION_BACKEND: "argo"
  TRAINING_ENABLED: "false"
  TRAINING_GPU_ENABLED: "false"
  TRAINING_GPU_COUNTS: ""
  HARBOR_REGISTRY_URL: "registry.mlops-nids-nt114.id.vn"
  HARBOR_USER_PROJECT: "user-images"
  GITHUB_OAUTH_REDIRECT_URI: "https://mlops-nids-nt114.id.vn/oauth/github/callback"
  CORS_ALLOWED_ORIGINS: "https://mlops-nids-nt114.id.vn,http://localhost:5173,http://127.0.0.1:5173"
  ARGO_BUILD_WEBHOOK_URL: "http://webhook-eventsource-eventsource-svc.argo-events.svc.cluster.local:12000/build"
  ARGO_TRAINING_WEBHOOK_URL: ""
  ARGO_CANCEL_TRAINING_WEBHOOK_URL: ""
  ARGO_DEPLOY_WEBHOOK_URL: "http://webhook-eventsource-eventsource-svc.argo-events.svc.cluster.local:12000/deploy"
  ARGO_DELETE_WEBHOOK_URL: "http://webhook-eventsource-eventsource-svc.argo-events.svc.cluster.local:12000/delete"
  ARGO_DRIFT_WEBHOOK_URL: "http://webhook-eventsource-eventsource-svc.argo-events.svc.cluster.local:12000/drift"
  AWS_DEFAULT_REGION: "ap-southeast-1"
  AWS_BUCKET_NAME: "mlops-paas-artifacts"
  KAFKA_TOPIC: "mlops_paas_production_data"
  REDPANDA_BROKERS: "redpanda-service.mlops-redpanda.svc.cluster.local:9092"
  JWKS_URL: "http://mlops-paas-control-plane.mlops-control-plane.svc.cluster.local:8000/api/auth/.well-known/jwks.json"
  REDIS_URL: "redis://mlops-paas-redis.mlops-redis.svc.cluster.local:6379/1"
  CELERY_BROKER_URL: "redis://mlops-paas-redis.mlops-redis.svc.cluster.local:6379/3"
  CELERY_RESULT_BACKEND: "redis://mlops-paas-redis.mlops-redis.svc.cluster.local:6379/4"
  REDIS_HOST: "mlops-paas-redis.mlops-redis.svc.cluster.local"
  REDIS_PORT: "6379"
  CONTROL_PLANE_INTERNAL_URL: "http://mlops-paas-control-plane.mlops-control-plane.svc.cluster.local:8000"
  MODEL_RUNTIME_NAMESPACE: "mlops-model-runtimes"
  MODEL_SERVER_PUBLIC_URL: "https://mlops-nids-nt114.id.vn"
  MODEL_SERVER_INTERNAL_URL: "http://traefik.kube-system.svc.cluster.local:5000"
  MLFLOW_TRACKING_URI: "http://mlflow-server.mlflow-server.svc.cluster.local:5000"
  MLFLOW_TRACKING_REQUIRED: "true"
  PROMETHEUS_INTERNAL_URL: "http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"

