apiVersion: v1
kind: Service
metadata:
  name: mlops-paas-control-plane
  labels:
    app: mlops-paas-control-plane
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  selector:
    app: mlops-paas-control-plane
