apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster.yaml
  - addons.yaml
  - platform.yaml
  - execution.yaml
  - workloads.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AppProject
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "-100"
