# Generated by Django 5.0.3 on 2026-07-12 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriftRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('external_run_id', models.CharField(blank=True, max_length=255)),
                ('current_data_uri', models.CharField(blank=True, max_length=1024)),
                ('report_html_uri', models.CharField(blank=True, max_length=1024)),
                ('report_json_uri', models.CharField(blank=True, max_length=1024)),
                ('summary_uri', models.CharField(blank=True, max_length=1024)),
                ('drift_score', models.FloatField(blank=True, null=True)),
                ('has_drift', models.BooleanField(null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriftMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('trigger_threshold', models.PositiveIntegerField(default=1000)),
                ('backend', models.CharField(default='docker', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drift_monitors', to='catalog.workspaceasset')),
            ],
        ),
    ]
