# Generated by Django 5.0.3 on 2026-07-12 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drift', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driftmonitor',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_monitors', to='registry.modelversion'),
        ),
        migrations.AddField(
            model_name='driftrun',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='drift.driftmonitor'),
        ),
        migrations.AddConstraint(
            model_name='driftmonitor',
            constraint=models.UniqueConstraint(fields=('version', 'name'), name='drift_version_name_unique'),
        ),
    ]
