# Generated by Django 5.0.3 on 2026-09-23 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_modelproject_lifecycle_status_and_more'),
        ('drift', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driftmonitor',
            name='reference_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drift_monitors', to='catalog.workspaceasset'),
        ),
    ]
