# Generated by Django 5.0.3 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drift", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driftmonitor",
            name="last_automatic_trigger_count",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
