# Generated by Django 5.0.3 on 2026-10-03 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_modelproject_active_deployment_modelpreview_and_more"),
        ("drift", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driftmonitor",
            name="reference_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="driftmonitor",
            name="reference_uri",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="driftmonitor",
            name="reference_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drift_monitors",
                to="catalog.workspaceasset",
            ),
        ),
    ]
