# Generated by Django 5.0.3 on 2026-10-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0003_driftmonitor_reference_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driftrun',
            name='dispatch_deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driftrun',
            name='execution_check_lease_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driftrun',
            name='execution_check_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driftrun',
            name='execution_deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driftrun',
            name='execution_stop_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driftrun',
            name='next_execution_check_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='driftrun',
            name='observation_error',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='driftrun',
            name='observation_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driftrun',
            name='observation_status',
            field=models.CharField(choices=[('ok', 'OK'), ('retrying', 'Retrying'), ('cleanup_pending', 'Cleanup pending')], default='ok', max_length=20),
        ),
        migrations.AddField(
            model_name='driftrun',
            name='runtime_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
