# Generated by Django 5.0.3 on 2026-09-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0003_alter_driftmonitor_reference_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driftmonitor',
            name='reference_asset',
        ),
    ]
