# Generated by Django 5.0.3 on 2026-10-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drift', '0004_driftrun_dispatch_deadline_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driftrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='pending', max_length=30),
        ),
    ]
