apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-paas-web
  labels:
    app: mlops-paas-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-paas-web
  template:
    metadata:
      labels:
        app: mlops-paas-web
    spec:
      nodeSelector:
        workload-type: worker
      containers:
        - name: web
          image: mlops-paas-web
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
