apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - external-secrets.yaml
  - rbac.yaml
  - training-namespace.yaml
  - eventbus.yaml
  - eventsource.yaml
  - webhook-service.yaml
  - network-policies.yaml
  - workflows/build-workflowtemplate.yaml
  - workflows/deploy-workflowtemplate.yaml
  - workflows/delete-workflowtemplate.yaml
  - workflows/evidently-workflowtemplate.yaml
  - workflows/training-workflowtemplate.yaml
  - workflows/training-cancel-workflowtemplate.yaml
  - sensor.yaml
