apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job-operations-rbac.yaml
  - workflows/job-operations-workflowtemplate.yaml
  - configmap.yaml
  - external-secrets.yaml
  - rbac.yaml
  - training-namespace.yaml
  - eventbus.yaml
  - eventsource.yaml
  - webhook-service.yaml
  - network-policies.yaml
  - workflows/build-workflowtemplate.yaml
  - workflows/deploy-workflowtemplate.yaml
  - workflows/delete-workflowtemplate.yaml
  - workflows/evidently-workflowtemplate.yaml
  - workflows/training-workflowtemplate.yaml
  - workflows/training-cancel-workflowtemplate.yaml
  - sensor.yaml

configMapGenerator:
  - name: argo-job-operations
    namespace: mlops-execution
    files:
      - scripts/job_ops.py
generatorOptions:
  disableNameSuffixHash: true
