apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-secret-sync
  namespace: mlflow-server
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef: {name: aws-secrets-manager, kind: ClusterSecretStore}
  target:
    name: mlflow-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - {secretKey: DB_USER, remoteRef: {key: mlops/production-secrets, property: DB_USER}}
    - {secretKey: DB_PASSWORD, remoteRef: {key: mlops/production-secrets, property: DB_PASSWORD}}
