# Generated by Django 5.0.3 on 2026-09-15 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('observed_at', models.DateTimeField()),
                ('features', models.JSONField(default=dict)),
                ('prediction', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('positive_class_probability', models.FloatField(blank=True, null=True)),
                ('class_mapping', models.JSONField(blank=True, default=dict)),
                ('decision_threshold', models.FloatField(blank=True, null=True)),
                ('calibration_version', models.CharField(blank=True, max_length=80)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
            },
        ),
    ]
