# Generated by Django 5.0.3 on 2026-09-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('production', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionrecord',
            name='model_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_records', to='registry.modelversion'),
        ),
        migrations.AddField(
            model_name='predictionrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_records', to='catalog.modelproject'),
        ),
        migrations.AddIndex(
            model_name='predictionrecord',
            index=models.Index(fields=['model_version', '-observed_at'], name='prod_version_observed_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionrecord',
            index=models.Index(fields=['project', '-observed_at'], name='prod_project_observed_idx'),
        ),
        migrations.AddConstraint(
            model_name='predictionrecord',
            constraint=models.CheckConstraint(check=models.Q(('positive_class_probability__isnull', True), models.Q(('positive_class_probability__gte', 0), ('positive_class_probability__lte', 1)), _connector='OR'), name='production_probability_range'),
        ),
        migrations.AddConstraint(
            model_name='predictionrecord',
            constraint=models.CheckConstraint(check=models.Q(('decision_threshold__isnull', True), models.Q(('decision_threshold__gte', 0), ('decision_threshold__lte', 1)), _connector='OR'), name='production_threshold_range'),
        ),
        migrations.AddConstraint(
            model_name='predictionrecord',
            constraint=models.CheckConstraint(check=models.Q(('latency_ms__isnull', True), ('latency_ms__gte', 0), _connector='OR'), name='production_latency_nonnegative'),
        ),
    ]
