apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-ha-secret-sync
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: redis-ha-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: mlops/production-secrets
        property: REDIS_PASSWORD
    - secretKey: REDIS_SENTINEL_PASSWORD
      remoteRef:
        key: mlops/production-secrets
        property: REDIS_SENTINEL_PASSWORD
