apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlops-redis

resources:
  - external-secrets.yaml
  - redis-config.yaml
  - replication.yaml
  - sentinel.yaml
  - network-policy.yaml
