apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-ha-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  redis-additional.conf: |
    appendonly yes
    appendfsync everysec
    maxmemory-policy noeviction
