apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: control-plane-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames: [mlops-control-plane]
  selector:
    matchLabels:
      app: mlops-paas-control-plane
  endpoints:
    - port: http
      path: /health/metrics
      interval: 15s
      scrapeTimeout: 10s
