from typing import Protocol


class BuildBackend(Protocol):
    def run(self, build): ...
    def cancel(self, build): ...


class TrainingBackend(Protocol):
    def run(self, job): ...
    def cancel(self, job): ...


class DeploymentBackend(Protocol):
    def deploy(self, deployment): ...
    def stop(self, deployment): ...
    def health(self, deployment): ...


class DriftBackend(Protocol):
    def run(self, drift_run): ...
