# Generated by Django 5.0.3 on 2026-07-12 03:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('flavor', models.CharField(max_length=80)),
                ('artifact_format', models.CharField(default='raw', max_length=20)),
                ('requirements_snapshot', models.TextField(blank=True)),
                ('backend', models.CharField(default='docker', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('building', 'Building'), ('ready', 'Ready'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('external_build_id', models.CharField(blank=True, max_length=255)),
                ('image_uri', models.CharField(blank=True, max_length=1024)),
                ('image_digest', models.CharField(blank=True, max_length=255)),
                ('package_uri', models.CharField(blank=True, max_length=1024)),
                ('logs', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildInputAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('source_artifact', 'Source Artifact'), ('label_mapping', 'Label Mapping'), ('metrics', 'Metrics'), ('params', 'Parameters'), ('model_insights', 'Model Insights'), ('feature_importance', 'Feature Importance'), ('input_schema', 'Input Schema')], max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('s3_uri', models.CharField(blank=True, max_length=1024)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=160)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('backend', models.CharField(default='docker', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deploying', 'Deploying'), ('healthy', 'Healthy'), ('unhealthy', 'Unhealthy'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=30)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('external_deployment_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_url', models.CharField(max_length=1024)),
                ('internal_url', models.CharField(blank=True, max_length=1024)),
                ('runtime_name', models.CharField(blank=True, max_length=255)),
                ('runtime_namespace', models.CharField(blank=True, max_length=255)),
                ('health_status', models.CharField(default='unknown', max_length=30)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
