# Generated by Django 5.0.3 on 2026-09-23 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0002_initial'),
        ('registry', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='registered_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_build', to='registry.modelversion'),
        ),
        migrations.AddField(
            model_name='build',
            name='source_draft_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='source_kind',
            field=models.CharField(choices=[('draft', 'Draft'), ('model_version', 'Model Version'), ('training_job', 'Training Job')], default='draft', max_length=30),
        ),
        migrations.AddField(
            model_name='build',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_builds', to='registry.modelversion'),
        ),
        migrations.AlterField(
            model_name='buildinputasset',
            name='kind',
            field=models.CharField(choices=[('model', 'Model Artifact'), ('reference_data', 'Reference Data'), ('source_code', 'Source Code'), ('source_artifact', 'Source Artifact'), ('training_output', 'Training Output'), ('label_mapping', 'Label Mapping'), ('data_contract', 'Data Contract'), ('metrics', 'Metrics'), ('params', 'Parameters'), ('model_insights', 'Model Insights'), ('feature_importance', 'Feature Importance'), ('input_schema', 'Input Schema')], max_length=40),
        ),
    ]
