# Generated by Django 5.0.3 on 2026-10-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_modelproject_active_deployment_modelpreview_and_more"),
        ("deployment", "0003_deployment_unconfirmed"),
        ("registry", "0003_remove_modelversion_registry_source_job_unique_and_more"),
        ("training", "0002_trainingjob_reference_path_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="build",
            name="build_active_source_job_unique",
        ),
        migrations.AddField(
            model_name="build",
            name="insights_summary",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="build",
            name="metrics_summary",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="build",
            name="params_summary",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="build",
            name="preview_revision",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="build",
            name="registration_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="build",
            name="registration_status",
            field=models.CharField(
                choices=[
                    ("unregistered", "Unregistered"),
                    ("registering", "Registering"),
                    ("registered", "Registered"),
                    ("failed", "Failed"),
                ],
                default="unregistered",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="buildinputasset",
            name="kind",
            field=models.CharField(
                choices=[
                    ("source_artifact", "Source Artifact"),
                    ("source_code", "Source Code"),
                    ("reference_data", "Reference Data"),
                    ("training_output", "Training Output"),
                    ("label_mapping", "Label Mapping"),
                    ("metrics", "Metrics"),
                    ("params", "Parameters"),
                    ("model_insights", "Model Insights"),
                    ("feature_importance", "Feature Importance"),
                    ("input_schema", "Input Schema"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="build",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_job__isnull", False), ("status__in", ("pending", "queued", "building"))),
                fields=("source_job",),
                name="build_active_source_job_unique",
            ),
        ),
    ]
