# Generated by Django 5.0.3 on 2026-09-24 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_modeldraft_status_draftassetupload_and_more'),
        ('deployment', '0003_build_registered_version_build_source_draft_revision_and_more'),
        ('registry', '0004_alter_modelartifact_kind'),
        ('training', '0002_alter_trainingoutput_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='registered_version',
        ),
        migrations.RemoveField(
            model_name='build',
            name='source_job_reference',
        ),
        migrations.RemoveField(
            model_name='build',
            name='source_kind',
        ),
        migrations.AddField(
            model_name='build',
            name='insights_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='build',
            name='metrics_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='build',
            name='params_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deployment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='catalog.modelproject'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='target',
            field=models.CharField(blank=True, choices=[('staging', 'Staging'), ('production', 'Production')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='source_draft_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='builds', to='catalog.modeldraftrevision'),
        ),
        migrations.AlterField(
            model_name='build',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='registry.modelversion'),
        ),
        migrations.AlterField(
            model_name='buildinputasset',
            name='kind',
            field=models.CharField(choices=[('model', 'Model Artifact'), ('reference_data', 'Reference Data'), ('source_code', 'Source Code'), ('label_mapping', 'Label Mapping'), ('data_contract', 'Data Contract'), ('metrics', 'Metrics'), ('params', 'Parameters'), ('model_insights', 'Model Insights'), ('feature_importance', 'Feature Importance'), ('input_schema', 'Input Schema')], max_length=40),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='deployment.build'),
        ),
        migrations.AddConstraint(
            model_name='build',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('source_draft_revision__isnull', False), ('source_job__isnull', True), ('source_version__isnull', True)), models.Q(('source_draft_revision__isnull', True), ('source_job__isnull', True), ('source_version__isnull', False)), models.Q(('source_draft_revision__isnull', True), ('source_job__isnull', False), ('source_version__isnull', True)), _connector='OR'), name='build_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'deploying', 'healthy'))), fields=('project', 'target'), name='deployment_active_target_project_unique'),
        ),
    ]
