# Generated by Django 5.0.3 on 2026-10-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deployment", "0004_remove_build_build_active_source_job_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildinputasset",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
