# Generated by Django 5.0.3 on 2026-09-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_modeldraft_source_version'),
        ('deployment', '0005_require_deployment_target_project'),
        ('registry', '0007_remove_modelversion_stage'),
        ('training', '0002_alter_trainingoutput_kind'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='build',
            name='build_exactly_one_source',
        ),
        migrations.AddField(
            model_name='build',
            name='source_job_reference',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='build',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('source_draft_revision__isnull', False), ('source_job__isnull', True), ('source_job_reference__isnull', True), ('source_version__isnull', True)), models.Q(('source_draft_revision__isnull', True), ('source_job__isnull', True), ('source_job_reference__isnull', True), ('source_version__isnull', False)), models.Q(('source_draft_revision__isnull', True), ('source_job_reference__isnull', False), ('source_version__isnull', True)), _connector='OR'), name='build_exactly_one_source'),
        ),
    ]
