# Generated by Django 5.0.3 on 2026-10-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0008_local_execution_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='source_output_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
