# Generated by Django 5.0.3 on 2026-09-15 09:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('pass', 'Pass'), ('fail', 'Fail'), ('hold', 'Hold'), ('error', 'Error')], default='pending', max_length=16)),
                ('metric_name', models.CharField(blank=True, max_length=80)),
                ('candidate_value', models.FloatField(blank=True, null=True)),
                ('champion_value', models.FloatField(blank=True, null=True)),
                ('delta', models.FloatField(blank=True, null=True)),
                ('margin', models.FloatField(blank=True, null=True)),
                ('historical_result', models.JSONField(blank=True, default=dict)),
                ('evidence_uri', models.CharField(blank=True, max_length=1024)),
                ('evidence_checksum', models.CharField(blank=True, max_length=128)),
                ('reason', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ordinal', models.PositiveBigIntegerField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('prediction_manifest_uri', models.CharField(blank=True, max_length=1024)),
                ('prediction_manifest_checksum', models.CharField(blank=True, max_length=128)),
                ('sample_count', models.PositiveBigIntegerField(default=0)),
                ('estimator', models.JSONField(blank=True, default=dict)),
                ('verification', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('collecting', 'Collecting'), ('sealed', 'Sealed'), ('awaiting_labels', 'Awaiting labels'), ('decided', 'Decided'), ('invalid', 'Invalid')], default='collecting', max_length=32)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceWindowSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pool', models.CharField(choices=[('hidden', 'Hidden'), ('verify', 'Verify'), ('train', 'Train'), ('gate', 'Gate')], default='hidden', max_length=16)),
                ('randomized_rank', models.PositiveBigIntegerField()),
                ('quality_status', models.CharField(choices=[('unchecked', 'Unchecked'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='unchecked', max_length=16)),
                ('quality_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('true_label', models.TextField()),
                ('source', models.CharField(choices=[('human', 'Human'), ('evaluator', 'Evaluator'), ('import', 'Import')], max_length=16)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('revealed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabelBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('episode_key', models.CharField(max_length=160)),
                ('total_quota', models.PositiveIntegerField()),
                ('verify_quota', models.PositiveIntegerField(default=0)),
                ('train_quota', models.PositiveIntegerField(default=0)),
                ('gate_quota', models.PositiveIntegerField(default=0)),
                ('verify_held', models.PositiveIntegerField(default=0)),
                ('train_held', models.PositiveIntegerField(default=0)),
                ('gate_held', models.PositiveIntegerField(default=0)),
                ('verify_used', models.PositiveIntegerField(default=0)),
                ('train_used', models.PositiveIntegerField(default=0)),
                ('gate_used', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('exhausted', 'Exhausted'), ('closed', 'Closed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabelLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('verify', 'Verify'), ('train', 'Train'), ('gate', 'Gate')], max_length=16)),
                ('entry_type', models.CharField(choices=[('reserve', 'Reserve'), ('commit', 'Commit'), ('release', 'Release')], max_length=16)),
                ('units', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('verify', 'Verify'), ('train', 'Train'), ('gate', 'Gate')], max_length=16)),
                ('seed', models.BigIntegerField()),
                ('request_round', models.PositiveSmallIntegerField()),
                ('requested_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabelRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('revealed', 'Revealed'), ('released', 'Released'), ('rejected', 'Rejected')], default='reserved', max_length=16)),
                ('unit_cost', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('evaluation_attempt', models.PositiveSmallIntegerField(default=1)),
                ('action', models.CharField(choices=[('keep', 'Keep'), ('request_labels', 'Request labels'), ('hold', 'Hold'), ('retrain', 'Retrain')], max_length=24)),
                ('reason_code', models.CharField(max_length=80)),
                ('reason_detail', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('verify_label_count', models.PositiveIntegerField(default=0)),
                ('train_label_count', models.PositiveIntegerField(default=0)),
                ('gate_label_count', models.PositiveIntegerField(default=0)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('policy_kind', models.CharField(choices=[('b0', 'B0'), ('b1', 'B1'), ('b2', 'B2'), ('b3', 'B3'), ('b4', 'B4'), ('b5', 'B5')], max_length=4)),
                ('config', models.JSONField(default=dict)),
                ('checksum', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(choices=[('awaiting_execution', 'Awaiting Execution'), ('running', 'Running'), ('awaiting_gate', 'Awaiting Gate'), ('awaiting_update', 'Awaiting Update'), ('applied', 'Applied'), ('failed', 'Failed'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='awaiting_execution', max_length=32)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceStepAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('step', models.CharField(choices=[('snapshot', 'Snapshot'), ('training', 'Training'), ('build', 'Build'), ('gate', 'Gate'), ('update', 'Update'), ('verify_runtime', 'Verify runtime')], max_length=32)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('backend', models.CharField(max_length=30)),
                ('workflow_uid', models.CharField(blank=True, max_length=255)),
                ('workload_uid', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], default='pending', max_length=16)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('initial_train', 'Initial train'), ('calibration', 'Calibration'), ('reference', 'Reference'), ('retrain', 'Retrain'), ('gate', 'Gate'), ('historical_holdout', 'Historical holdout')], max_length=32)),
                ('manifest_uri', models.CharField(max_length=1024)),
                ('manifest_checksum', models.CharField(max_length=128)),
                ('schema_checksum', models.CharField(max_length=128)),
                ('code_checksum', models.CharField(blank=True, max_length=128)),
                ('code_snapshot_uri', models.CharField(blank=True, max_length=1024)),
                ('row_count', models.PositiveBigIntegerField(default=0)),
                ('recipe_version', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_snapshots', to='catalog.modelproject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
