# Generated by Django 5.0.3 on 2026-09-15 09:49

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('ct', '0001_initial'),
        ('deployment', '0001_initial'),
        ('drift', '0001_initial'),
        ('production', '0001_initial'),
        ('registry', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationgate',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_evaluation_gates', to='registry.modelversion'),
        ),
        migrations.AddField(
            model_name='evaluationgate',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='champion_evaluation_gates', to='registry.modelversion'),
        ),
        migrations.AddField(
            model_name='evaluationgate',
            name='gate_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_gates', to='ct.datasetsnapshot'),
        ),
        migrations.AddField(
            model_name='evidencewindow',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='champion_evidence_windows', to='registry.modelversion'),
        ),
        migrations.AddField(
            model_name='evidencewindow',
            name='drift_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_windows', to='drift.driftrun'),
        ),
        migrations.AddField(
            model_name='evidencewindow',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_windows', to='catalog.modelproject'),
        ),
        migrations.AddField(
            model_name='evidencewindow',
            name='reference_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_evidence_windows', to='ct.datasetsnapshot'),
        ),
        migrations.AddField(
            model_name='datasetsnapshot',
            name='source_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_snapshots', to='ct.evidencewindow'),
        ),
        migrations.AddField(
            model_name='evidencewindowsample',
            name='prediction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_window_sample', to='production.predictionrecord'),
        ),
        migrations.AddField(
            model_name='evidencewindowsample',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='ct.evidencewindow'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='prediction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='production.predictionrecord'),
        ),
        migrations.AddField(
            model_name='labelbudget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_budgets', to='catalog.modelproject'),
        ),
        migrations.AddField(
            model_name='labelledgerentry',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='ct.labelbudget'),
        ),
        migrations.AddField(
            model_name='labelrequest',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='ct.labelbudget'),
        ),
        migrations.AddField(
            model_name='labelrequest',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_requests', to='ct.evidencewindow'),
        ),
        migrations.AddField(
            model_name='labelledgerentry',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='ct.labelrequest'),
        ),
        migrations.AddField(
            model_name='labelrequestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ct.labelrequest'),
        ),
        migrations.AddField(
            model_name='labelrequestitem',
            name='window_sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='label_request_item', to='ct.evidencewindowsample'),
        ),
        migrations.AddField(
            model_name='labelledgerentry',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='ct.labelrequestitem'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='request_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='ct.labelrequestitem'),
        ),
        migrations.AddField(
            model_name='maintenancedecision',
            name='expected_champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_decisions', to='registry.modelversion'),
        ),
        migrations.AddField(
            model_name='maintenancedecision',
            name='training_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_decisions', to='training.trainingjob'),
        ),
        migrations.AddField(
            model_name='maintenancedecision',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='ct.evidencewindow'),
        ),
        migrations.AddField(
            model_name='maintenancepolicy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_policies', to='catalog.modelproject'),
        ),
        migrations.AddField(
            model_name='maintenancedecision',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='ct.maintenancepolicy'),
        ),
        migrations.AddField(
            model_name='evidencewindow',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_windows', to='ct.maintenancepolicy'),
        ),
        migrations.AddField(
            model_name='maintenancerun',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_maintenance_runs', to='registry.modelversion'),
        ),
        migrations.AddField(
            model_name='maintenancerun',
            name='dataset_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_runs', to='ct.datasetsnapshot'),
        ),
        migrations.AddField(
            model_name='maintenancerun',
            name='decision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_run', to='ct.maintenancedecision'),
        ),
        migrations.AddField(
            model_name='maintenancerun',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_runs', to='deployment.deployment'),
        ),
        migrations.AddField(
            model_name='maintenancerun',
            name='expected_champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expected_maintenance_runs', to='registry.modelversion'),
        ),
        migrations.AddField(
            model_name='maintenancerun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_runs', to='catalog.modelproject'),
        ),
        migrations.AddField(
            model_name='maintenancerun',
            name='training_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_runs', to='training.trainingjob'),
        ),
        migrations.AddField(
            model_name='evaluationgate',
            name='run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_gate', to='ct.maintenancerun'),
        ),
        migrations.AddField(
            model_name='maintenancestepattempt',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_attempts', to='ct.maintenancerun'),
        ),
        migrations.AddConstraint(
            model_name='evidencewindowsample',
            constraint=models.UniqueConstraint(fields=('window', 'pool', 'randomized_rank'), name='ct_window_pool_rank_unique'),
        ),
        migrations.AddConstraint(
            model_name='labelbudget',
            constraint=models.UniqueConstraint(fields=('project', 'episode_key'), name='ct_budget_project_episode_unique'),
        ),
        migrations.AddConstraint(
            model_name='labelbudget',
            constraint=models.CheckConstraint(check=models.Q(('verify_quota__lte', models.F('total_quota')), ('train_quota__lte', models.F('total_quota')), ('gate_quota__lte', models.F('total_quota'))), name='ct_budget_purpose_quota_valid'),
        ),
        migrations.AddConstraint(
            model_name='labelbudget',
            constraint=models.CheckConstraint(check=models.Q(('verify_held__lte', django.db.models.expressions.CombinedExpression(models.F('verify_quota'), '-', models.F('verify_used'))), ('train_held__lte', django.db.models.expressions.CombinedExpression(models.F('train_quota'), '-', models.F('train_used'))), ('gate_held__lte', django.db.models.expressions.CombinedExpression(models.F('gate_quota'), '-', models.F('gate_used')))), name='ct_budget_purpose_usage_valid'),
        ),
        migrations.AddConstraint(
            model_name='labelbudget',
            constraint=models.CheckConstraint(check=models.Q(('verify_quota__gte', django.db.models.expressions.CombinedExpression(models.F('verify_held'), '+', models.F('verify_used'))), ('train_quota__gte', django.db.models.expressions.CombinedExpression(models.F('train_held'), '+', models.F('train_used'))), ('gate_quota__gte', django.db.models.expressions.CombinedExpression(models.F('gate_held'), '+', models.F('gate_used')))), name='ct_budget_purpose_total_valid'),
        ),
        migrations.AddConstraint(
            model_name='labelbudget',
            constraint=models.CheckConstraint(check=models.Q(('total_quota__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('verify_held'), '+', models.F('verify_used')), '+', models.F('train_held')), '+', models.F('train_used')), '+', models.F('gate_held')), '+', models.F('gate_used')))), name='ct_budget_total_usage_valid'),
        ),
        migrations.AddConstraint(
            model_name='labelrequest',
            constraint=models.UniqueConstraint(fields=('window', 'purpose', 'request_round'), name='ct_request_window_purpose_round'),
        ),
        migrations.AddConstraint(
            model_name='maintenancepolicy',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='ct_policy_project_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='maintenancepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project',), name='ct_one_active_policy_per_project'),
        ),
        migrations.AddConstraint(
            model_name='maintenancedecision',
            constraint=models.UniqueConstraint(fields=('window', 'policy', 'evaluation_attempt'), name='ct_decision_window_policy_attempt'),
        ),
        migrations.AddConstraint(
            model_name='evidencewindow',
            constraint=models.UniqueConstraint(fields=('project', 'policy', 'ordinal'), name='ct_window_project_policy_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='evidencewindow',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__gt', models.F('starts_at'))), name='ct_window_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerun',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('awaiting_execution', 'running', 'awaiting_gate', 'awaiting_update'))), fields=('project',), name='ct_one_active_run_per_project'),
        ),
        migrations.AddConstraint(
            model_name='evaluationgate',
            constraint=models.CheckConstraint(check=models.Q(('candidate', models.F('champion')), _negated=True), name='ct_gate_distinct_versions'),
        ),
        migrations.AddConstraint(
            model_name='maintenancestepattempt',
            constraint=models.UniqueConstraint(fields=('run', 'step', 'attempt_number'), name='ct_step_run_attempt_unique'),
        ),
    ]
