# Generated by Django 5.0.3 on 2026-07-12 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproject',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceasset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_assets', to='catalog.modelproject'),
        ),
        migrations.AddIndex(
            model_name='modelproject',
            index=models.Index(fields=['owner', 'is_active'], name='project_owner_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='modelproject',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='project_owner_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='workspaceasset',
            constraint=models.UniqueConstraint(fields=('project', 'kind', 'relative_path'), name='workspace_asset_path_unique'),
        ),
    ]
