# Generated by Django 5.0.3 on 2026-09-23 04:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('deployment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelproject',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='modelproject',
            name='task_domain',
            field=models.CharField(choices=[('binary_classification', 'Binary Classification'), ('multiclass_classification', 'Multiclass Classification'), ('regression', 'Regression'), ('ranking', 'Ranking'), ('general', 'General')], default='binary_classification', max_length=64),
        ),
        migrations.CreateModel(
            name='ModelDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('flavor', models.CharField(blank=True, max_length=80)),
                ('artifact_format', models.CharField(choices=[('raw', 'Raw'), ('archive', 'Archive')], default='raw', max_length=20)),
                ('requirements_snapshot', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('saved_revision', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('editing', 'Editing'), ('ready', 'Ready'), ('locked', 'Locked')], default='editing', max_length=20)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by_build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_drafts', to='deployment.build')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='catalog.modelproject')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('model', 'Model Artifact'), ('reference_data', 'Reference Baseline Data'), ('source_code', 'Source Code'), ('label_mapping', 'Label Mapping'), ('data_contract', 'Data Contract'), ('metrics', 'Metrics'), ('params', 'Parameters'), ('model_insights', 'Model Insights'), ('feature_importance', 'Feature Importance'), ('input_schema', 'Input Schema')], max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('s3_uri', models.CharField(max_length=1024)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='catalog.modeldraft')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='draftasset',
            constraint=models.UniqueConstraint(fields=('draft', 'kind'), name='draft_asset_kind_unique'),
        ),
    ]
