# Generated by Django 5.0.3 on 2026-09-24 17:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_modelproject_lifecycle_status_and_more'),
        ('drift', '0004_remove_driftmonitor_reference_asset'),
        ('registry', '0004_alter_modelartifact_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldraft',
            name='status',
            field=models.CharField(choices=[('editing', 'Editing'), ('saving', 'Saving'), ('ready', 'Ready'), ('locked', 'Locked')], default='editing', max_length=20),
        ),
        migrations.CreateModel(
            name='DraftAssetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(max_length=40)),
                ('object_key', models.CharField(max_length=1024, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(max_length=128)),
                ('content_type', models.CharField(max_length=160)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='catalog.modeldraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_asset_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelDraftRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.PositiveIntegerField()),
                ('flavor', models.CharField(blank=True, max_length=80)),
                ('artifact_format', models.CharField(default='raw', max_length=20)),
                ('requirements_snapshot', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='catalog.modeldraft')),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_revisions', to='registry.modelversion')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='DraftRevisionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=1024)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='catalog.modeldraftrevision')),
            ],
        ),
        migrations.AddField(
            model_name='modeldraft',
            name='saved_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_drafts', to='catalog.modeldraftrevision'),
        ),
        migrations.DeleteModel(
            name='WorkspaceAsset',
        ),
        migrations.AddConstraint(
            model_name='modeldraftrevision',
            constraint=models.UniqueConstraint(fields=('draft', 'number'), name='draft_revision_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='draftrevisionasset',
            constraint=models.UniqueConstraint(fields=('revision', 'kind'), name='draft_revision_asset_kind_unique'),
        ),
    ]
