# Generated by Django 5.0.3 on 2026-10-03 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_project_active_name_unique"),
        ("deployment", "0003_deployment_unconfirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelproject",
            name="active_deployment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_projects",
                to="deployment.deployment",
            ),
        ),
        migrations.CreateModel(
            name="ModelPreview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("flavor", models.CharField(blank=True, max_length=80)),
                ("artifact_format", models.CharField(default="raw", max_length=20)),
                ("requirements_text", models.TextField(blank=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="preview", to="catalog.modelproject"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreviewAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("source_artifact", "Source Artifact"),
                            ("source_code", "Source Code"),
                            ("reference_data", "Reference Data"),
                            ("label_mapping", "Label Mapping"),
                            ("metrics", "Metrics"),
                            ("params", "Params"),
                            ("model_insights", "Model Insights"),
                            ("feature_importance", "Feature Importance"),
                            ("input_schema", "Input Schema"),
                        ],
                        max_length=40,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("s3_uri", models.CharField(max_length=1024)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=160)),
                (
                    "preview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assets", to="catalog.modelpreview"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="previewasset",
            constraint=models.UniqueConstraint(fields=("preview", "kind"), name="preview_asset_kind_unique"),
        ),
    ]
