# Generated by Django 5.0.3 on 2026-09-25 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_modeldraft_status_draftassetupload_and_more'),
        ('registry', '0007_remove_modelversion_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldraft',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaded_drafts', to='registry.modelversion'),
        ),
    ]
