# Generated by Django 5.0.3 on 2026-09-15 09:49

import apps.observability.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(default=apps.observability.models.new_idempotency_key, max_length=255, unique=True)),
                ('delivery_kind', models.CharField(choices=[('kafka', 'Kafka'), ('webhook', 'Webhook')], max_length=16)),
                ('destination', models.CharField(max_length=255)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(auto_now_add=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['delivery_kind', 'published_at', 'available_at'], name='outbox_delivery_ready_idx'), models.Index(fields=['locked_until'], name='outbox_lease_idx')],
            },
        ),
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=60)),
                ('from_state', models.CharField(blank=True, max_length=80)),
                ('to_state', models.CharField(blank=True, max_length=80)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('maintenance_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events', to='catalog.modelproject')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='lifecycle_project_created_idx'), models.Index(fields=['aggregate_type', 'aggregate_id', 'created_at'], name='life_aggregate_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='lifecycleevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('aggregate_type', 'aggregate_id', 'idempotency_key'), name='lifecycle_event_idempotency_unique'),
        ),
    ]
